spring.application.name=kms-backend

# Chuỗi kết nối PostgreSQL lấy trực tiếp từ màn hình Supabase của bạn
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.sbdmfrfpzfmsuvdxaqxx
# Thay thế [YOUR-PASSWORD] bằng mật khẩu bạn tự đặt lúc tạo dự án kms-drone
spring.datasource.password=kms-drone-group2
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate tự động cập nhật hoặc tạo bảng sang Supabase khi chạy Spring Boot
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8080